version: "3.7"
services:
  redis:
    image: redis:alpine
    networks:
      - internal
    ports:
      - "6379"
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:12-alpine
    networks:
      - internal
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  backend:
    build:
      context: '.'
      dockerfile: Dockerfile-backend
    volumes:
      - .:/var/hs-forum/
      - stack-data:/root/.stack
    networks:
      - internal
    ports: 
      - "3000:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PASSWORD=password

  frontend:
    image: nginx:alpine
    networks:
      - internal
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./webroot/:/usr/share/nginx/html/:ro
    environment:
      - NGINX_HOST=localhost

volumes:
  pg-data:
  stack-data:

networks:
  internal:
