version: "3.7"
services:
  redis:
    image: redis:alpine
    networks:
      - internal
    ports:
      - "6379"
    volumes:
      - redis-data:/DATA
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:12-alpine
    networks:
      - internal
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  backend:
    image: hs-forum/prod
    init: true
    ports: 
      - "8080"
    networks:
      - internal
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PASSWORD=password

  frontend:
    image: nginx:alpine
    networks:
      - internal
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./webroot:/usr/share/nginx/html:ro

volumes:
  pg-data:
  redis-data:

networks:
  internal:
