FROM ubuntu:18.04 as base
RUN apt-get update && apt-get install -y \
  libgmp10 \
  libpq-dev

FROM base as stack-base
ARG STACK_RESOLVER=lts-14.27
RUN apt-get install -y curl
RUN curl -sSL https://get.haskellstack.org/ | sh
ENV PATH="/root/.local/bin:${PATH}"
RUN stack setup --allow-different-user --resolver=$STACK_RESOLVER
COPY backend/stack.yaml .
COPY backend/package.yaml .
RUN stack build --only-dependencies
FROM stack-base as dev
RUN stack install ghcid
VOLUME /var/hs-forum
WORKDIR /var/hs-forum
CMD ["bash", "run-dev.sh"]

FROM stack-base as builder
COPY backend /var/hs-forum
WORKDIR /var/hs-forum
RUN stack install --allow-different-user .

FROM base as prod
COPY --from=builder /root/.local/bin /root/.local/bin
COPY --from=builder /var/hs-forum/config.yaml config.yaml
COPY --from=fpco/pid1 /sbin/pid1 /sbin/pid1
CMD ["/sbin/pid1", "/root/.local/bin/hs-forum-exe"]
